version: '3.8'

services:
  traefik:
    image: traefik:v2.3
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --api.insecure=true
      - --providers.docker=true

  flask-api:
    image: flask-api
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask-api.rule=Host(`flask-api.localhost`)"
      - "traefik.http.services.flask-api.loadbalancer.server.port=5000"
    depends_on:
      - traefik